export const advantagesPrompList = [
    "Die Sicht deiner Feinde ist eingeschränkt",
    "Deine Feinde sind plötzlich Abgelenkt", 
    "Ein Umgebung verändert sich zu deinem Vorteil", 
    "Ein Weg wird für deine Feinde versperrt", 
    "Die Umgebung verändert sich zum Nachteil deiner Feinde", 
    "Ein Feuer bricht aus",
    "Wasser dringt ein",
    "Etwas explodiert",
    "Ein Transportmittel fällt aus", 
    "Ein Einsturz droht",
    "Deine Gegner sind entwaffnet",
    "Dein Gegner verliehrt etwas das er wieder braucht",
    "Du findest etwas wertvolles oder interessantes",
    "Ein Gerät funktioniert nur eingeschränkt bis es repariert werden kann",
    "Deine Gegner wird zu Boden gerissen",
    "Dein Gegner kannst seine Beine nicht benutzen",
    "Dein Gegner kannst eine oder beide Hände nicht benutzen",
    "Einer der Sinne deines Gegners fällt aus",
    "Dein Gegner fällt in Ohnmacht",
    "Ein Fluchtweg entsteht oder offenbahrt sich",
    "Deine Gegenspieler werden demoralisiert",
    "Deine Handlung bringt dir Rum und Dankbarkeit ein",
    "Etwas stellt sich als etwas komplett anderes heraus",
    "Jemand übersieht etwas",
    "Die Person die du gerade am meisten gebrauchen kannst steht hinter dir",
    "Eine bisher unbeteiligte Partei wird einbezogen, und sie ist auf deiner Seite",
    "Deine Handlung bringt jemand anderes in Bedrängniss"
]