export const diceButtonTextArray = [
    "Roll 'em bones!",
    "Let's roll!",
    "Getting dicey!",
    "Here goes nothing",
    "Come on, big crits!",
    "Snake eyes!",
    "Alea iacta est",
    "Just roll already",
    "Come on, big money!",
    "Keep on rolling, rolling",
    "Going critical!",
    "Hope this works",
    "RNGesus take the wheel!",
    "RNGesus save me",
    "May the force be with you",
    "What would RNGesus do?",
    "I like big crits and I cannto lie",
    "Never tell me the odds",
    "*sweating profusely*",
    "Well, good luck!",
    "Sweet baby RNGesus!",
    "Thats a lota dice",
    "I like those odds", 
    "May the odds ever be in your favor",
    "This is gonna sting",
    "What could possibly go wrong?",
    "Whats the worst that could happen?",
    "*chuckles* I'm in danger!",
    "*nervous chuckle*",
    "Oh. Oh no."
]