export const disadvantagesPrompList = [
    "Die Sichtbdingungen werden schlechter", 
    "Der Boden wird unpassierbar", 
    "Ein vorteilhaftes Stück Umgebung wird unbrauchbar", 
    "Ein Weg wird für dich versperrt", 
    "Eine Barrikade gibt überraschend nach",
    "Ein Alarm erklingt", 
    "Ein Feuer bricht aus",
    "Wasser dringt ein",
    "Etwas explodiert",
    "Ein Transportmittel fällt aus", 
    "Ein Einsturz droht",
    "Munition, Treibstoff oder Batterien gehen verlohren",
    "Etwas von Wert fällt aus deiner Tasche",
    "Verpflegung wird unbrauchbar oder Riskant zu nutzen",
    "Ein Gerät funktioniert nur eingeschränkt bis es repariert werden kann",
    "Du wirst zu Boden gerissen",
    "Du kannst deine Beine nicht benutzen",
    "Du kannst eine oder beide Hände nicht benutzen",
    "Einer deiner Sinne fällt aus",
    "Das wird eine Narbe geben",
    "Du ziehst dir eine Vergiftung oder Krankheit zu",
    "Dir wird Schwarz vor Augen",
    "Vorher Verborgene Feinde erscheinen",
    "Du sinkst in der Meinung der Anwesenden",
    "Etwas stellt sich als etwas komplett anderes heraus",
    "Diese Handlung wird vom Gesetzt geahndet",
    "Du hörst wie sich eine Bedrohung nähert",
    "Dein Geist ist verwirrt",
    "Eine verborgene Falle offenbahrt sich",
    "Die Person die du gerade am wenigsten gebrauchen kannst steht vor dir",
    "Eine bisher unbeteiligte Partei wird einbezogen, und sie ist gegen dich",
    "Ein unbequemer Zeuge hat alles gesehen",
    "Deine Handlung bringt jemand anderes in Bedrängniss"
]